const STAGES = ['Connecting', 'Discovering subdomains', 'Resolving and checking', 'Preparing results'];
const els = {
  form: document.getElementById('scanForm'), domain: document.getElementById('domain'), scan: document.getElementById('scanButton'), cancel: document.getElementById('cancelButton'),
  status: document.getElementById('statusBadge'), error: document.getElementById('domain-error'), progress: document.getElementById('progressLine'), progressText: document.getElementById('progressText'), success: document.getElementById('successLine'),
  panel: document.getElementById('resultsPanel'), resultsBox: document.getElementById('resultsBox'), count: document.getElementById('resultCount'), metricDomain: document.getElementById('metricDomain'), metricDuration: document.getElementById('metricDuration'),
  copy: document.getElementById('copyButton'), csv: document.getElementById('csvButton'), clear: document.getElementById('clearButton')
};
let controller = null; let currentResults = []; let stageTimer = null;
function normalizeDomain(value) { return value.trim().toLowerCase().replace(/^https?:\/\//, '').split('/')[0].replace(/\.$/, ''); }
function isValidDomain(value) { const domain = normalizeDomain(value); if (!domain || domain.length > 253 || domain.includes(':') || domain.includes('/') || !domain.includes('.')) return false; const labels = domain.split('.'); return labels.every((label) => label.length <= 63 && /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/.test(label)) && /^[a-z]{2,63}$/.test(labels.at(-1)); }
function setStatus(value) { els.status.textContent = value; els.status.className = `status-badge ${value.toLowerCase().replaceAll(' ', '-')}`; }
function setError(message) { els.error.textContent = message; els.error.classList.toggle('show', Boolean(message)); els.domain.setAttribute('aria-invalid', message ? 'true' : 'false'); }
function setScanning(active) { els.domain.disabled = active; els.scan.classList.toggle('hidden', active); els.cancel.classList.toggle('hidden', !active); els.progress.classList.toggle('hidden', !active); els.success.classList.add('hidden'); }
function formatDuration(ms) { return ms < 1000 ? `${ms} ms` : `${(ms / 1000).toFixed(2)} s`; }
function stageLoop() { let index = 0; els.progressText.textContent = STAGES[index]; stageTimer = window.setInterval(() => { index = Math.min(index + 1, STAGES.length - 1); els.progressText.textContent = STAGES[index]; }, 900); }
function renderResults(domain, results, duration) { els.panel.classList.remove('hidden'); els.metricDomain.textContent = domain; els.metricDuration.textContent = formatDuration(duration); els.count.textContent = String(results.length); els.resultsBox.innerHTML = ''; if (!results.length) { const empty = document.createElement('div'); empty.className = 'empty-result'; empty.innerHTML = `<div class="empty-icon">🟠</div><h3>No 🟠 Cloudflare subdomains were found for ${escapeHtml(domain)}.</h3><p>Certificate Transparency does not guarantee every DNS subdomain is discoverable.</p>`; els.resultsBox.appendChild(empty); } else { for (const result of results) { const row = document.createElement('div'); row.className = 'result-row'; row.innerHTML = `<span class="orange-dot">🟠</span><code>${escapeHtml(result.hostname)}</code><span class="dash">—</span><code class="ip">${escapeHtml(result.ip)}</code><button class="icon-btn" type="button" aria-label="Copy result">⧉</button>`; row.querySelector('button').addEventListener('click', () => navigator.clipboard.writeText(`🟠 ${result.hostname} — ${result.ip}`)); els.resultsBox.appendChild(row); } } els.copy.disabled = results.length === 0; els.csv.disabled = results.length === 0; }
function escapeHtml(value) { const div = document.createElement('div'); div.textContent = value; return div.innerHTML; }
function plainText() { return currentResults.map((r) => `🟠 ${r.hostname} — ${r.ip}`).join('\n'); }
function csvEscape(value) { const text = String(value); return /[",\n\r]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
els.form.addEventListener('submit', async (event) => { event.preventDefault(); const domain = normalizeDomain(els.domain.value); setError(''); els.panel.classList.add('hidden'); currentResults = []; if (!isValidDomain(domain)) { setStatus('Error'); setError('Please enter a valid domain, for example: speedtest.net'); return; } controller = new AbortController(); setScanning(true); setStatus('Connecting'); stageLoop(); try { const response = await fetch('/api/scan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ domain }), signal: controller.signal }); let data = null; try { data = await response.json(); } catch { throw new Error('The server returned an invalid response.'); } if (!response.ok || !data.success) throw new Error(data.error?.message || 'The scan could not be completed.'); currentResults = Array.isArray(data.results) ? data.results.filter((r) => r && r.cloudflare === true && r.hostname && r.ip) : []; setStatus('Complete'); renderResults(data.domain || domain, currentResults, Number(data.duration_ms) || 0); els.progress.classList.add('hidden'); els.success.classList.remove('hidden'); } catch (error) { if (error.name === 'AbortError') { setStatus('Ready'); setError('Scan canceled.'); } else { setStatus('Error'); setError(error.message || 'The scan could not be completed.'); } } finally { window.clearInterval(stageTimer); stageTimer = null; setScanning(false); controller = null; } });
els.cancel.addEventListener('click', () => controller?.abort());
els.copy.addEventListener('click', async () => { if (!currentResults.length) return; await navigator.clipboard.writeText(plainText()); const old = els.copy.textContent; els.copy.textContent = 'Copied ✓'; window.setTimeout(() => { els.copy.textContent = old; }, 1400); });
els.csv.addEventListener('click', () => { if (!currentResults.length) return; const lines = ['hostname,ip,cloudflare', ...currentResults.map((r) => `${csvEscape(r.hostname)},${csvEscape(r.ip)},true`)]; const blob = new Blob([`${lines.join('\n')}\n`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${normalizeDomain(els.domain.value) || 'orange-test'}-cloudflare.csv`; a.click(); URL.revokeObjectURL(url); });
els.clear.addEventListener('click', () => { controller?.abort(); els.domain.value = ''; currentResults = []; els.panel.classList.add('hidden'); setError(''); setStatus('Ready'); });
